# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontend.proto\"\x19\n\nIntegerArg\x12\x0b\n\x03\x61rg\x18\x01 \x01(\x05\":\n\x06GetKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08\x43lientId\x18\x02 \x01(\x03\x12\x11\n\tRequestId\x18\x03 \x01(\x03\"K\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08\x43lientId\x18\x03 \x01(\x03\x12\x11\n\tRequestId\x18\x04 \x01(\x03\":\n\x05Reply\x12\x13\n\x0bwrongLeader\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t2\x84\x01\n\x08\x46rontEnd\x12\x18\n\x03Get\x12\x07.GetKey\x1a\x06.Reply\"\x00\x12\x1a\n\x03Put\x12\t.KeyValue\x1a\x06.Reply\"\x00\x12\x1e\n\x07Replace\x12\t.KeyValue\x1a\x06.Reply\"\x00\x12\"\n\tStartRaft\x12\x0b.IntegerArg\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTEGERARG']._serialized_start=18
  _globals['_INTEGERARG']._serialized_end=43
  _globals['_GETKEY']._serialized_start=45
  _globals['_GETKEY']._serialized_end=103
  _globals['_KEYVALUE']._serialized_start=105
  _globals['_KEYVALUE']._serialized_end=180
  _globals['_REPLY']._serialized_start=182
  _globals['_REPLY']._serialized_end=240
  _globals['_FRONTEND']._serialized_start=243
  _globals['_FRONTEND']._serialized_end=375
# @@protoc_insertion_point(module_scope)
