# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import frontend_pb2 as frontend__pb2


class FrontEndStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/FrontEnd/Get',
                request_serializer=frontend__pb2.GetKey.SerializeToString,
                response_deserializer=frontend__pb2.Reply.FromString,
                )
        self.Put = channel.unary_unary(
                '/FrontEnd/Put',
                request_serializer=frontend__pb2.KeyValue.SerializeToString,
                response_deserializer=frontend__pb2.Reply.FromString,
                )
        self.Replace = channel.unary_unary(
                '/FrontEnd/Replace',
                request_serializer=frontend__pb2.KeyValue.SerializeToString,
                response_deserializer=frontend__pb2.Reply.FromString,
                )
        self.StartRaft = channel.unary_unary(
                '/FrontEnd/StartRaft',
                request_serializer=frontend__pb2.IntegerArg.SerializeToString,
                response_deserializer=frontend__pb2.Reply.FromString,
                )


class FrontEndServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRaft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontEndServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=frontend__pb2.GetKey.FromString,
                    response_serializer=frontend__pb2.Reply.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=frontend__pb2.KeyValue.FromString,
                    response_serializer=frontend__pb2.Reply.SerializeToString,
            ),
            'Replace': grpc.unary_unary_rpc_method_handler(
                    servicer.Replace,
                    request_deserializer=frontend__pb2.KeyValue.FromString,
                    response_serializer=frontend__pb2.Reply.SerializeToString,
            ),
            'StartRaft': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRaft,
                    request_deserializer=frontend__pb2.IntegerArg.FromString,
                    response_serializer=frontend__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FrontEnd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FrontEnd(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FrontEnd/Get',
            frontend__pb2.GetKey.SerializeToString,
            frontend__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FrontEnd/Put',
            frontend__pb2.KeyValue.SerializeToString,
            frontend__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Replace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FrontEnd/Replace',
            frontend__pb2.KeyValue.SerializeToString,
            frontend__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartRaft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FrontEnd/StartRaft',
            frontend__pb2.IntegerArg.SerializeToString,
            frontend__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
