# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyvaluestore.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13keyvaluestore.proto\"\x07\n\x05\x45mpty\":\n\x05Reply\x12\x13\n\x0bwrongLeader\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\'\n\x05State\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08isLeader\x18\x02 \x01(\x08\"4\n\x08LogEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\"\x92\x01\n\x14\x41ppendEntriesRequest\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x14\n\x0cprefixLength\x18\x03 \x01(\x05\x12\x12\n\nprefixTerm\x18\x04 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x06 \x03(\x0b\x32\t.LogEntry\"_\n\x12\x41ppendEntriesReply\x12\x12\n\nfollowerId\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x16\n\x0enewAckedLength\x18\x03 \x01(\x05\x12\x0f\n\x07success\x18\x04 \x01(\x05\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\".\n\tVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\":\n\x06GetKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08\x43lientId\x18\x02 \x01(\x03\x12\x11\n\tRequestId\x18\x03 \x01(\x03\"K\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08\x43lientId\x18\x03 \x01(\x03\x12\x11\n\tRequestId\x18\x04 \x01(\x03\x32\xe9\x01\n\rKeyValueStore\x12\x1c\n\x08GetState\x12\x06.Empty\x1a\x06.State\"\x00\x12\x18\n\x03Get\x12\x07.GetKey\x1a\x06.Reply\"\x00\x12\x1a\n\x03Put\x12\t.KeyValue\x1a\x06.Reply\"\x00\x12\x1e\n\x07Replace\x12\t.KeyValue\x1a\x06.Reply\"\x00\x12;\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x13.AppendEntriesReply\x12\'\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\n.VoteReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyvaluestore_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_REPLY']._serialized_start=32
  _globals['_REPLY']._serialized_end=90
  _globals['_STATE']._serialized_start=92
  _globals['_STATE']._serialized_end=131
  _globals['_LOGENTRY']._serialized_start=133
  _globals['_LOGENTRY']._serialized_end=185
  _globals['_APPENDENTRIESREQUEST']._serialized_start=188
  _globals['_APPENDENTRIESREQUEST']._serialized_end=334
  _globals['_APPENDENTRIESREPLY']._serialized_start=336
  _globals['_APPENDENTRIESREPLY']._serialized_end=431
  _globals['_VOTEREQUEST']._serialized_start=433
  _globals['_VOTEREQUEST']._serialized_end=524
  _globals['_VOTEREPLY']._serialized_start=526
  _globals['_VOTEREPLY']._serialized_end=572
  _globals['_GETKEY']._serialized_start=574
  _globals['_GETKEY']._serialized_end=632
  _globals['_KEYVALUE']._serialized_start=634
  _globals['_KEYVALUE']._serialized_end=709
  _globals['_KEYVALUESTORE']._serialized_start=712
  _globals['_KEYVALUESTORE']._serialized_end=945
# @@protoc_insertion_point(module_scope)
