# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import keyvaluestore_pb2 as keyvaluestore__pb2


class KeyValueStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/KeyValueStore/GetState',
                request_serializer=keyvaluestore__pb2.Empty.SerializeToString,
                response_deserializer=keyvaluestore__pb2.State.FromString,
                )
        self.Get = channel.unary_unary(
                '/KeyValueStore/Get',
                request_serializer=keyvaluestore__pb2.GetKey.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Reply.FromString,
                )
        self.Put = channel.unary_unary(
                '/KeyValueStore/Put',
                request_serializer=keyvaluestore__pb2.KeyValue.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Reply.FromString,
                )
        self.Replace = channel.unary_unary(
                '/KeyValueStore/Replace',
                request_serializer=keyvaluestore__pb2.KeyValue.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Reply.FromString,
                )
        self.AppendEntries = channel.unary_unary(
                '/KeyValueStore/AppendEntries',
                request_serializer=keyvaluestore__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.AppendEntriesReply.FromString,
                )
        self.RequestVote = channel.unary_unary(
                '/KeyValueStore/RequestVote',
                request_serializer=keyvaluestore__pb2.VoteRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.VoteReply.FromString,
                )


class KeyValueStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=keyvaluestore__pb2.Empty.FromString,
                    response_serializer=keyvaluestore__pb2.State.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=keyvaluestore__pb2.GetKey.FromString,
                    response_serializer=keyvaluestore__pb2.Reply.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=keyvaluestore__pb2.KeyValue.FromString,
                    response_serializer=keyvaluestore__pb2.Reply.SerializeToString,
            ),
            'Replace': grpc.unary_unary_rpc_method_handler(
                    servicer.Replace,
                    request_deserializer=keyvaluestore__pb2.KeyValue.FromString,
                    response_serializer=keyvaluestore__pb2.Reply.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=keyvaluestore__pb2.AppendEntriesRequest.FromString,
                    response_serializer=keyvaluestore__pb2.AppendEntriesReply.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=keyvaluestore__pb2.VoteRequest.FromString,
                    response_serializer=keyvaluestore__pb2.VoteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/GetState',
            keyvaluestore__pb2.Empty.SerializeToString,
            keyvaluestore__pb2.State.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/Get',
            keyvaluestore__pb2.GetKey.SerializeToString,
            keyvaluestore__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/Put',
            keyvaluestore__pb2.KeyValue.SerializeToString,
            keyvaluestore__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Replace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/Replace',
            keyvaluestore__pb2.KeyValue.SerializeToString,
            keyvaluestore__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/AppendEntries',
            keyvaluestore__pb2.AppendEntriesRequest.SerializeToString,
            keyvaluestore__pb2.AppendEntriesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/RequestVote',
            keyvaluestore__pb2.VoteRequest.SerializeToString,
            keyvaluestore__pb2.VoteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
